import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import {useEffect, useRef, useState} from 'react'
import React from 'react';
import {Line} from 'react-chartjs-2';


export default function Home() {
  const router = useRouter()
  const [test,setTest]=useState("این یک متن تست است")
  const [copied,setCopied]=useState(false)
  const [view,setView]=useState(0)
  const [connectionStatus,setConnectionStatus]=useState<boolean | null>(null)
  const status = useRef<any>()
  const handleCopy = () => {
    navigator.clipboard.writeText(test).then(()=>{
      setCopied(true)
    })
  }
  
  useEffect(()=>{
    // console.log(navigator.onLine)

      if(navigator.onLine){
        setConnectionStatus(true)
      }else{
        setConnectionStatus(false)
      }
    

  
  },[])
  console.log(connectionStatus)
  useEffect(()=>{
    if(copied){
      setTimeout(()=>{
        setCopied(false)
      },2000)
    }
  },[copied])
  const handleNavigate = () =>{
    router.push('/circle ')
    
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleNavigate}>go other page</button>
      <Link href={"/videoplayer"} as="/mojtaba" hrefLang='en'>video player</Link>
      <Link href={"/circle"}>circle</Link>
      <Link href={"/skeleton"} className="mx-20">skeletons</Link>
      <div>
        <Link href={test === "test" ? '/gooz' : '/goh'}>
          link
        </Link>
     </div>
      <button onClick={handleCopy}>
        {
          copied ? 'copied!':'click to copy'
        }
        
      </button>
      <div ref={status}>
        {connectionStatus ? 'online' : 'offline'}
      </div>
      view of page {view}
    </div>
  );
}
